# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Diosa
email: diosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Uma plataforma de divulgação de mão de obra feminina na área de manutenção geral de residências.
register_button: >
  Cadastre-se para se manter informado
we_do: >
  O que fazemos
description_we_do: >
  Nós divulgamos a mão de obra feminina ligada à manutenção geral de residências, possibilitando mais visibilidade para as mulheres que já trabalham na área e para aquelas que estão buscando inserção nesse mercado
spread: >
  a mão de obra feminina relacionada à manutenção geral de residências.
potencialize: >
  o interesse de outras mulheres em fazer parte desse mercado.
helps: >
  a qualificação e também a inserção delas no mercado de trabalho.
encourage: >
  mulheres a trabalhar em uma área incomum para elas.
we_are: >
  Quem somos
description_we_are: >
  A Diosa é formada por 4 mulheres que acreditam no empreendedorismo social, na necessidade de discussão sobre estereótipos de gênero e no empoderamento feminino para mudança social.
  Por isso, investimos na divulgação da mão de obra feminina em uma área pouco comum para elas, mas que existe uma grande demanda de clientes a ser atendida.
partners: >
  Parceiros
be_partner: >
  Seja nosso parceiro
contact: >
  Contato
description_contact: >
  Tem interesse em saber mais sobre a Diosa, contratar o serviço ou ser uma prestadora? Entra em contato com a gente. Ficaremos felizes com o seu contato.
baseurl: "/diosa" # the subpath of your site, e.g. /blog
url: "http://diosa.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
